name: facetrip
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  auto_route: null
  bloc: null
  cloud_firestore: null
  cupertino_icons: null
  dartz: null
  equatable: null
  firebase_auth: null
  firebase_core: null
  firebase_storage: null
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_dotenv: null
  flutter_signin_button: null
  font_awesome_flutter: null
  freezed_annotation: null
  get_it: null
  injectable: null
  json_annotation: null
  path_provider: null
  reactive_forms: null
  rounded_loading_button: ^2.1.0

dev_dependencies:
  auto_route_generator: null

  # Freezed libraries
  build_runner: null
  flutter_lints: null
  flutter_test:
    sdk: flutter
  freezed: null

  injectable_generator: null

  json_serializable: null

flutter:
  uses-material-design: true

  assets:
    - .env
