// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8ZBmKa_WCm0PolES5Ez9rqVrFAe8h41Y',
    appId: '1:494310129751:web:d162e1dbb2248e4cfa2312',
    messagingSenderId: '494310129751',
    projectId: 'trip-dfae4',
    authDomain: 'trip-dfae4.firebaseapp.com',
    storageBucket: 'trip-dfae4.appspot.com',
    measurementId: 'G-LMW6CYTXHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4LF0Qz6RPklLHRGIN11aIdVc5FMTVRcw',
    appId: '1:494310129751:android:131f6eae48fb52e4fa2312',
    messagingSenderId: '494310129751',
    projectId: 'trip-dfae4',
    storageBucket: 'trip-dfae4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArZtUi7CI8tob2r6DDhjqSIpZKRGPjpbU',
    appId: '1:494310129751:ios:1b9c51f1a5fb4b09fa2312',
    messagingSenderId: '494310129751',
    projectId: 'trip-dfae4',
    storageBucket: 'trip-dfae4.appspot.com',
    iosClientId: '494310129751-fqlnpuqriv9kf2t2bhgri1tcmo9dd06j.apps.googleusercontent.com',
    iosBundleId: 'com.devally.facetrip',
  );
}
